---
- name: make a build dir
  file: state=directory name=/root/kibana-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/kibana-dockerized/Dockerfile

- name: put config.js
  template: src=config.js dest=/root/kibana-dockerized/config.js

- name: put default
  template: src=default dest=/root/kibana-dockerized/default

- name: build a Docker image for Kibana
  command: docker build -t gitinsky/kibana:0.1.0 --rm /root/kibana-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/kibana:latest --rm /root/kibana-dockerized
