---
- name: make a build dir
  file: state=directory name=/root/kibana-dockerized
  tags: 
    - docker
    - kibana

- name: put Dockerfile
  template: src=Dockerfile dest=/root/kibana-dockerized/Dockerfile
  tags: 
    - docker
    - kibana

- name: build a Docker image for Kibana
  command: docker build --no-cache -t gitinsky/kibana:{{ kibana_version }}.0 -t gitinsky/kibana:latest --rm /root/kibana-dockerized
  tags:
    - docker
    - kibana
